sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t webapp -f Dockerfile.dev .

script:
  - docker run -e CI=true webapp npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-968338625147"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id:
    secure: "ovm5cZazv91JRYI05QIO1OqDGFZgYepbA8+qvKXO4b3vqOgtJVBxintUzHTT8KYNWlt3s3Klw0vMYJBPc1XgFxne7UoQbBEl87Fd69dZFDKDwMOOHjwyNVLWW6TVoITneYC5l/qpKMQk6sAlfa7uQeJ5Vk9SLNqfAEFaPD2PQzUuYVxe/R5dpsjHiAwvLJCNWAc185os7enj+BvfSeiSaFPvoYL1Uk3mXmZno/jkphQBWzl+WRYyre/PHWan2bBXY7IxxOqwcSBE4t4taGnWgKc5tCBNTxpyX6fAuSglFobLyyqgo8V6BFPVN571ZFhCSC2jnVG1WV9jUqSIyRLdvSS9R0DUf2Vs9ikYhtRZ+XhF/9zPeZddkt9tn8ATLX9oveLNImZubKpC1pwe25HMe0YQNU+T//skLwHk2hfPnlZpqEbbFkmR3qhfvF/iLbKi4lDq8VyE+MTK33CqS/AJ/p0Y2O7FEXKpKghsVZJAh1vE0WP39p+rxE5X2v2/6QHVcCS0NifzB1Bx5W7LLxLubTjWCfrJ3AOqkoXzsJnErdCa+fDPI9c6zDmQLZb82oMh6Ce/1peF9svucOeD/gr3ULO1EtjBNawTAxttU6NLhNoulNiLqIFzwmKOMSSDy0IsW+VEOo4BRrbowSRUW+8YLBvfp2ndeBEHe9HwB+J4lbU="
  secret_access_key:
    secure: "RLg1Xc/jbEqzOBdAjbqPtUtO6TspoHjM8xbJnb9jYKrUtHl/Nztaxw6Pc88FmCrTUOctxjmYan+h8x9pZ5N6nrYAlcnO6vABfln4wqVTgdojIogUJVVG2WjZQFkSU8Ebkx7lkmozestCjG1Z8/FBBHU2W1oeKTVPlkk7novgrmUGz/6FUN3bqj8DmeSVk1Q5bV4UrQeRHQCfmMKvWkOQbQkZ7WzGq4+RX2cqzRZwyVJ60f8taIszsldv4woWd4QnvnfVW3yIKkOKSKHurojzqA+1I8hYRsLH1ZRNd7wld8vKc0RVUSmvxxycJPr1MigX1A6/jnqRV3IobBrv+k+WWQdqeUj1gUhco3hirS6a7GHluBy/0UVwk9WrZNqchd9kSr+bg9hEeBt9eR3OwwUsB3wSGZsGQqd8WwepGEXSDU3hWoEIFrhaa3pucLlejiuS+ib81Wz0kzHamSlds7e7oGSwTc2HYsC6gGGh7gM06Ok+O1FvLp8x1SZGDpiBy2NkhMchQriiM3tulxTocdKhVYDHv5lrt6CIRLi1QNe87Udfic0rHZxjSgqpNFHmxep0lzPWhDXnwuy8Z+0HUaNdApij9sJJiG/3hclSavvy6eUJ1bPdbvXX7j8ds1ODnfE5xJRnUaMJDjgRSqjfR7Cw/Q1T95Ke/+xAGYXVakxCh0M="